#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain_information () {
    local line
    line=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    printf "The subdomain %s is a %s record and points to %s\n" "$2" "$line"
}

if [ "$#" == 1 ]; then
    for subdomain in "www" "lb-01" "web-01" "web-02"; do
        domain_information "$1" "$subdomain"
    done
elif [ "$#" == 2 ]; then
    domain_information "$1" "$2"
fi
