#!/bin/bash

# Install Nginx web server if not installed
apt-get update -y
apt-get install -y nginx

# Create a sample HTML file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx to serve the sample HTML file
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
" > /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
service nginx restart
