#!/usr/bin/env bash
# This script configures Nginx to have a custom 404 page

sudo sed -i '/^\tlocation \/ {/a \\tlocation = /404.html {\\n\t\tinternal;\\n\t}\\n\\terror_page 404 /404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
