#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP header to its response

sudo apt-get update
sudo apt-get install -y nginx
echo 'add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/sites-available/default
# Restart Nginx to apply changes
sudo service nginx restart
