#!/usr/bin/env bash
# This script configures Nginx on a new Ubuntu machine to include a custom HTTP header.

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure Nginx with custom header
echo "add_header X-Served-By \$(hostname);" | sudo tee -a /etc/nginx/sites-available/default
sudo service nginx restart
