#!/usr/bin/env bash
# This script installs and configures HAproxy on a new Ubuntu machine
# to load balance between web-01 and web-02.

# Install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAproxy
sudo echo "frontend lb-frontend
    bind *:80
    mode http
    default_backend lb-backend

backend lb-backend
    mode http
    balance roundrobin
    server web-01 312099-web-01:80 check
    server web-02 web-02:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy
sudo service haproxy restart
