#!/usr/bin/env bash
# This script installs and configures HAproxy on lb-01 server

# Install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAproxy
echo "
frontend web_front
    bind *:80
    mode http
    default_backend web_back

backend web_back
    mode http
    balance roundrobin
    server web-01 52.3.242.164:80 check
    server web-02 34.207.63.188:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy to apply changes
sudo service haproxy restart
