#!/bin/bash

# Create an RSA key pair with a passphrase

# Define variables
KEY_NAME="school"
BITS=4096
PASSPHRASE="betty"

# Generate the key pair
ssh-keygen -t rsa -b $BITS -f $KEY_NAME -N $PASSPHRASE

# Display the key fingerprint and randomart image
echo "Key fingerprint is:"
ssh-keygen -lf $KEY_NAME

# Move the public key to the correct filename
mv $KEY_NAME.pub $KEY_NAME.pub

# Display the content of the current directory
ls
